name: generate

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 1"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install ads titlecase tqdm matplotlib==3.1.0

      - name: Run scripts
        shell: bash -l {0}
        run: |
          make update
        env:
          ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Build the PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make luger_cv.pdf
            make luger_cv_academic.pdf

      - name: Publish
        shell: bash -l {0}
        run: |
          git checkout --orphan master-pdf
          git rm --cached -rf . > /dev/null 2>&1
          git add -f luger_cv.pdf luger_cv_academic.pdf
          git add -f pubs.json metrics.json stars.json citedates.txt
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "rebuild pdf"
          git push -q -f https://github.com/$GITHUB_REPOSITORY master-pdf > /dev/null 2>&1
